apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: project-1-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: project-1

  namespaceSelector:
    matchNames:
      - default

  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
