server:
  port: 8080

spring:
  application:
    name: demo

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

  metrics:
    export:
      prometheus:
        enabled: true
